### ISSUE TITLE
How to use require in the srcset attribute?

### ISSUE THREAD

**Issue by bparticle** [HCESrl/vue-responsive-image#1]
Hi,

I would love to use vue-responsive-image on my project, but can't get it to work in my template. I am using require() to load the appropriate image from a json object that contains the data, but it doesn't play well with the plugin.
`
<vue-responsive-image
      @click="goToItem"
      :image-url="require(`@/assets/work/${work.img}_%width%x%height%.jpg`)"
      :image-ratio="work.ratio"
      ></vue-responsive-image>
`
(Back ticks are not showing on the code preview)

When I omit the %width%x%height the image is loading but I don't get any responsive behavior of course.
Another issue I have is the @click event. That doesn't seem to stick.

**Comment by riveraeu** [comment]
You need to have some system that automatically generates the images for you when an URL with the appropriate format is called.

I use [https://cloudinary.com/](url) which offers a free service for storing and transforming your images. 
Once you upload an image to their cloud, just copy the URL and add the the **c_scale** transformation like so:

... upload/**c_scale,%width%,%height%**/v1529358740/....

then in the **ResponsiveImage.vue** component change the **getImageUrlWithWidthAndHeight** method like so: 
`return this.imageUrl.replace(this.widthPlaceholder, 'h_' + height).replace(this.heightPlaceholder, 'w_' + width)`

If you want to listen to a native event on the root element of a component, you have to use the .native modifier, like so `@click.native="someMethod"`

**Comment by pmioni** [comment]
This plugin only works, as  @riveraeu has pointed out, with a third-party service that generates images on the fly.
