### ISSUE TITLE
Vue 3 support ?

### ISSUE THREAD

**Issue by mits87** [HCESrl/vue-responsive-image#9]
Hi, 
is it possible to support Vue 3 of this plugin?
Thanks in advance.

**Comment by pmioni** [comment]
I'll look into it this week. Thanks for the request.

**Comment by pmioni** [comment]
@mits87 it will take some time to release that version, sorry.

**Comment by wobsoriano** [comment]
You can try to interop this component to Vue 3 using https://github.com/privatenumber/vue-2-3

See my implementation here https://codesandbox.io/s/vue3-infinite-loading-63rqj

**Comment by ecaterina-b** [comment]
@mits87 Hi, the new version 2.0 is compatible with Vue 3.

**Comment by pmioni** [comment]
@mits87 as @ecaterina-b pointed out, we have a Vue3 compatible version now. Sorry about the delay!
I'm closing this ticket now.
